# coding: utf-8

"""
    FINBOURNE Identity Service API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic.v1 import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from pydantic.v1 import Field, StrictInt
from typing import List, Optional
from typing_extensions import Annotated
from finbourne_identity.models.mcp_tool_response import McpToolResponse
from finbourne_identity.models.upsert_mcp_tool_request import UpsertMcpToolRequest

from finbourne_identity.api_client import ApiClient
from finbourne_identity.api_response import ApiResponse
from finbourne_identity.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from finbourne_identity.extensions.configuration_options import ConfigurationOptions

# ensure templated type usages are imported
from pydantic.v1 import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated

class MCPToolsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @overload
    async def create_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], upsert_mcp_tool_request : Annotated[UpsertMcpToolRequest, Field(description="The MCP tool definition")], **kwargs) -> McpToolResponse:  # noqa: E501
        ...

    @overload
    def create_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], upsert_mcp_tool_request : Annotated[UpsertMcpToolRequest, Field(description="The MCP tool definition")], async_req: Optional[bool]=True, **kwargs) -> McpToolResponse:  # noqa: E501
        ...

    @validate_arguments
    def create_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], upsert_mcp_tool_request : Annotated[UpsertMcpToolRequest, Field(description="The MCP tool definition")], async_req: Optional[bool]=None, **kwargs) -> Union[McpToolResponse, Awaitable[McpToolResponse]]:  # noqa: E501
        """[EARLY ACCESS] CreateMcpTool: Create an MCP Tool  # noqa: E501

        Creates a new MCP tool definition  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_mcp_tool(scope, code, upsert_mcp_tool_request, async_req=True)
        >>> result = thread.get()

        :param scope: The scope of the MCP tool (required)
        :type scope: str
        :param code: The code of the MCP tool (required)
        :type code: str
        :param upsert_mcp_tool_request: The MCP tool definition (required)
        :type upsert_mcp_tool_request: UpsertMcpToolRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: McpToolResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_mcp_tool_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.create_mcp_tool_with_http_info(scope, code, upsert_mcp_tool_request, **kwargs)  # noqa: E501

    @validate_arguments
    def create_mcp_tool_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], upsert_mcp_tool_request : Annotated[UpsertMcpToolRequest, Field(description="The MCP tool definition")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EARLY ACCESS] CreateMcpTool: Create an MCP Tool  # noqa: E501

        Creates a new MCP tool definition  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_mcp_tool_with_http_info(scope, code, upsert_mcp_tool_request, async_req=True)
        >>> result = thread.get()

        :param scope: The scope of the MCP tool (required)
        :type scope: str
        :param code: The code of the MCP tool (required)
        :type code: str
        :param upsert_mcp_tool_request: The MCP tool definition (required)
        :type upsert_mcp_tool_request: UpsertMcpToolRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(McpToolResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'upsert_mcp_tool_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_mcp_tool" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['upsert_mcp_tool_request'] is not None:
            _body_params = _params['upsert_mcp_tool_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '201': "McpToolResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.api_client.call_api(
            '/api/mcptools/{scope}/{code}', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def delete_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], **kwargs) -> None:  # noqa: E501
        ...

    @overload
    def delete_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], async_req: Optional[bool]=True, **kwargs) -> None:  # noqa: E501
        ...

    @validate_arguments
    def delete_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], async_req: Optional[bool]=None, **kwargs) -> Union[None, Awaitable[None]]:  # noqa: E501
        """[EARLY ACCESS] DeleteMcpTool: Delete an MCP Tool  # noqa: E501

        Deletes an MCP tool (soft delete - closes the current version)  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_mcp_tool(scope, code, async_req=True)
        >>> result = thread.get()

        :param scope: The scope of the MCP tool (required)
        :type scope: str
        :param code: The code of the MCP tool (required)
        :type code: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_mcp_tool_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.delete_mcp_tool_with_http_info(scope, code, **kwargs)  # noqa: E501

    @validate_arguments
    def delete_mcp_tool_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EARLY ACCESS] DeleteMcpTool: Delete an MCP Tool  # noqa: E501

        Deletes an MCP tool (soft delete - closes the current version)  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_mcp_tool_with_http_info(scope, code, async_req=True)
        >>> result = thread.get()

        :param scope: The scope of the MCP tool (required)
        :type scope: str
        :param code: The code of the MCP tool (required)
        :type code: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'scope',
            'code'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_mcp_tool" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {}

        return self.api_client.call_api(
            '/api/mcptools/{scope}/{code}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def get_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], version : Annotated[Optional[StrictInt], Field(description="Optional version number to retrieve. If not specified, returns the current version.")] = None, **kwargs) -> McpToolResponse:  # noqa: E501
        ...

    @overload
    def get_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], version : Annotated[Optional[StrictInt], Field(description="Optional version number to retrieve. If not specified, returns the current version.")] = None, async_req: Optional[bool]=True, **kwargs) -> McpToolResponse:  # noqa: E501
        ...

    @validate_arguments
    def get_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], version : Annotated[Optional[StrictInt], Field(description="Optional version number to retrieve. If not specified, returns the current version.")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[McpToolResponse, Awaitable[McpToolResponse]]:  # noqa: E501
        """[EARLY ACCESS] GetMcpTool: Get an MCP Tool  # noqa: E501

        Retrieves an MCP tool. If version is specified, retrieves that specific version for audit purposes. Otherwise, retrieves the current version.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_mcp_tool(scope, code, version, async_req=True)
        >>> result = thread.get()

        :param scope: The scope of the MCP tool (required)
        :type scope: str
        :param code: The code of the MCP tool (required)
        :type code: str
        :param version: Optional version number to retrieve. If not specified, returns the current version.
        :type version: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: McpToolResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_mcp_tool_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_mcp_tool_with_http_info(scope, code, version, **kwargs)  # noqa: E501

    @validate_arguments
    def get_mcp_tool_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], version : Annotated[Optional[StrictInt], Field(description="Optional version number to retrieve. If not specified, returns the current version.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EARLY ACCESS] GetMcpTool: Get an MCP Tool  # noqa: E501

        Retrieves an MCP tool. If version is specified, retrieves that specific version for audit purposes. Otherwise, retrieves the current version.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_mcp_tool_with_http_info(scope, code, version, async_req=True)
        >>> result = thread.get()

        :param scope: The scope of the MCP tool (required)
        :type scope: str
        :param code: The code of the MCP tool (required)
        :type code: str
        :param version: Optional version number to retrieve. If not specified, returns the current version.
        :type version: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(McpToolResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'version'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_mcp_tool" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        if _params.get('version') is not None:  # noqa: E501
            _query_params.append(('version', _params['version']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "McpToolResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.api_client.call_api(
            '/api/mcptools/{scope}/{code}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def list_mcp_tools(self, **kwargs) -> List[McpToolResponse]:  # noqa: E501
        ...

    @overload
    def list_mcp_tools(self, async_req: Optional[bool]=True, **kwargs) -> List[McpToolResponse]:  # noqa: E501
        ...

    @validate_arguments
    def list_mcp_tools(self, async_req: Optional[bool]=None, **kwargs) -> Union[List[McpToolResponse], Awaitable[List[McpToolResponse]]]:  # noqa: E501
        """[EARLY ACCESS] ListMcpTools: List all MCP Tools  # noqa: E501

        Lists all current MCP tools for the domain  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_mcp_tools(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[McpToolResponse]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_mcp_tools_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.list_mcp_tools_with_http_info(**kwargs)  # noqa: E501

    @validate_arguments
    def list_mcp_tools_with_http_info(self, **kwargs) -> ApiResponse:  # noqa: E501
        """[EARLY ACCESS] ListMcpTools: List all MCP Tools  # noqa: E501

        Lists all current MCP tools for the domain  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_mcp_tools_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[McpToolResponse], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_mcp_tools" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "List[McpToolResponse]",
        }

        return self.api_client.call_api(
            '/api/mcptools', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def update_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], upsert_mcp_tool_request : Annotated[UpsertMcpToolRequest, Field(description="The updated MCP tool definition")], **kwargs) -> McpToolResponse:  # noqa: E501
        ...

    @overload
    def update_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], upsert_mcp_tool_request : Annotated[UpsertMcpToolRequest, Field(description="The updated MCP tool definition")], async_req: Optional[bool]=True, **kwargs) -> McpToolResponse:  # noqa: E501
        ...

    @validate_arguments
    def update_mcp_tool(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], upsert_mcp_tool_request : Annotated[UpsertMcpToolRequest, Field(description="The updated MCP tool definition")], async_req: Optional[bool]=None, **kwargs) -> Union[McpToolResponse, Awaitable[McpToolResponse]]:  # noqa: E501
        """[EARLY ACCESS] UpdateMcpTool: Update an MCP Tool  # noqa: E501

        Updates an existing MCP tool, creating a new version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_mcp_tool(scope, code, upsert_mcp_tool_request, async_req=True)
        >>> result = thread.get()

        :param scope: The scope of the MCP tool (required)
        :type scope: str
        :param code: The code of the MCP tool (required)
        :type code: str
        :param upsert_mcp_tool_request: The updated MCP tool definition (required)
        :type upsert_mcp_tool_request: UpsertMcpToolRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: McpToolResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_mcp_tool_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.update_mcp_tool_with_http_info(scope, code, upsert_mcp_tool_request, **kwargs)  # noqa: E501

    @validate_arguments
    def update_mcp_tool_with_http_info(self, scope : Annotated[StrictStr, Field(..., description="The scope of the MCP tool")], code : Annotated[StrictStr, Field(..., description="The code of the MCP tool")], upsert_mcp_tool_request : Annotated[UpsertMcpToolRequest, Field(description="The updated MCP tool definition")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EARLY ACCESS] UpdateMcpTool: Update an MCP Tool  # noqa: E501

        Updates an existing MCP tool, creating a new version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_mcp_tool_with_http_info(scope, code, upsert_mcp_tool_request, async_req=True)
        >>> result = thread.get()

        :param scope: The scope of the MCP tool (required)
        :type scope: str
        :param code: The code of the MCP tool (required)
        :type code: str
        :param upsert_mcp_tool_request: The updated MCP tool definition (required)
        :type upsert_mcp_tool_request: UpsertMcpToolRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(McpToolResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'upsert_mcp_tool_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_mcp_tool" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['upsert_mcp_tool_request'] is not None:
            _body_params = _params['upsert_mcp_tool_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "McpToolResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.api_client.call_api(
            '/api/mcptools/{scope}/{code}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
