# coding: utf-8

"""
    FINBOURNE Identity Service API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class CellParentStatusResponse(BaseModel):
    """
    Response containing the current cell parent status.  # noqa: E501
    """
    status:  Optional[StrictStr] = Field(None,alias="status", description="The current attachment status of the cell.") 
    admin_domain_name:  Optional[StrictStr] = Field(None,alias="adminDomainName", description="The name of the admin domain in the parent cell, if any.") 
    primary_domain_name:  Optional[StrictStr] = Field(None,alias="primaryDomainName", description="The domain designated as the primary domain for this cell, if any.") 
    registration_step:  Optional[StrictStr] = Field(None,alias="registrationStep", description="The most recently reached registration checkpoint, or null if no registration has started. One of `UserEnsured`, `PATGenerated`, `PATPushed`.") 
    registration_error:  Optional[StrictStr] = Field(None,alias="registrationError", description="Operator-readable message describing the most recent registration failure, or null on success.") 
    __properties = ["status", "adminDomainName", "primaryDomainName", "registrationStep", "registrationError"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CellParentStatusResponse:
        """Create an instance of CellParentStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if status (nullable) is None
        # and __fields_set__ contains the field
        if self.status is None and "status" in self.__fields_set__:
            _dict['status'] = None

        # set to None if admin_domain_name (nullable) is None
        # and __fields_set__ contains the field
        if self.admin_domain_name is None and "admin_domain_name" in self.__fields_set__:
            _dict['adminDomainName'] = None

        # set to None if primary_domain_name (nullable) is None
        # and __fields_set__ contains the field
        if self.primary_domain_name is None and "primary_domain_name" in self.__fields_set__:
            _dict['primaryDomainName'] = None

        # set to None if registration_step (nullable) is None
        # and __fields_set__ contains the field
        if self.registration_step is None and "registration_step" in self.__fields_set__:
            _dict['registrationStep'] = None

        # set to None if registration_error (nullable) is None
        # and __fields_set__ contains the field
        if self.registration_error is None and "registration_error" in self.__fields_set__:
            _dict['registrationError'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CellParentStatusResponse:
        """Create an instance of CellParentStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CellParentStatusResponse.parse_obj(obj)

        _obj = CellParentStatusResponse.parse_obj({
            "status": obj.get("status"),
            "admin_domain_name": obj.get("adminDomainName"),
            "primary_domain_name": obj.get("primaryDomainName"),
            "registration_step": obj.get("registrationStep"),
            "registration_error": obj.get("registrationError")
        })
        return _obj

CellParentStatusResponse.update_forward_refs()
