# coding: utf-8

"""
    FINBOURNE Identity Service API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class SetAttachingKeyRequest(BaseModel):
    """
    Request body for setting the Attaching Key on a child cell. The three values together identify the parent admin domain, the parent's cell database row, and the PAT used to authenticate the attachment handshake.  # noqa: E501
    """
    pat:  StrictStr = Field(...,alias="pat", description="Attaching Key PAT issued by the parent admin portal's `BeginCellRegistration` endpoint. Length bounds match admin-ui's `RegisterDomainPatRequest`. We apply `StringSecurityCheck` (the Finbourne.Validation catch-all that the recorded baseline tolerates for opaque strings) AND a stricter regex restricting the value to the opaque-token character set so the request body cannot smuggle in HTML/SQL/ script content even if the catch-all is later relaxed.") 
    parent_domain_name:  StrictStr = Field(...,alias="parentDomainName", description="Parent admin domain name (as entered alongside the Attaching Key by the user). Used only as the initial proposal value; the admin domain stored in the DB is the source of truth for all later operations (anti-redirection).") 
    parent_assigned_cell_id: Optional[StrictInt] = Field(default=None, description="Database identifier of this cell in the parent admin-ui's `cell` table. Returned alongside the Attaching Key by the parent's `BeginCellRegistration` response and required to call `POST /admin-ui/api/domains/{cellId}/register` during the Finbourne.Lydia.Postgres.Database.DTO.RegistrationStep.PatPushed step.", alias="parentAssignedCellId")
    __properties = ["pat", "parentDomainName", "parentAssignedCellId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SetAttachingKeyRequest:
        """Create an instance of SetAttachingKeyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SetAttachingKeyRequest:
        """Create an instance of SetAttachingKeyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SetAttachingKeyRequest.parse_obj(obj)

        _obj = SetAttachingKeyRequest.parse_obj({
            "pat": obj.get("pat"),
            "parent_domain_name": obj.get("parentDomainName"),
            "parent_assigned_cell_id": obj.get("parentAssignedCellId")
        })
        return _obj

SetAttachingKeyRequest.update_forward_refs()
