# coding: utf-8

"""
    FINBOURNE Identity Service API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class SetParentCellRequest(BaseModel):
    """
    Request body for setting the parent cell.  # noqa: E501
    """
    admin_domain_name:  StrictStr = Field(...,alias="adminDomainName", description="The name of the admin domain in the parent cell.") 
    confirm: StrictBool = Field(description="Whether to confirm the parent cell attachment (second invocation). First call with false creates a Proposed state; second call with true transitions to Attaching.")
    __properties = ["adminDomainName", "confirm"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SetParentCellRequest:
        """Create an instance of SetParentCellRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SetParentCellRequest:
        """Create an instance of SetParentCellRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SetParentCellRequest.parse_obj(obj)

        _obj = SetParentCellRequest.parse_obj({
            "admin_domain_name": obj.get("adminDomainName"),
            "confirm": obj.get("confirm")
        })
        return _obj

SetParentCellRequest.update_forward_refs()
