# coding: utf-8

"""
    FINBOURNE Identity Service API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class UpdateSessionPolicyRequest(BaseModel):
    """
    Session timing settings.  # noqa: E501
    """
    max_session_idle_minutes: StrictInt = Field(description="Maximum minutes a user's session can be idle before re-authentication is required. Must be between 5 minutes and 12 hours (720 minutes).", alias="maxSessionIdleMinutes")
    max_session_lifetime_minutes: Optional[StrictInt] = Field(default=None, description="Maximum minutes a user's session can live in total. Omit to disable session expiry; otherwise must be between 5 minutes and 24 hours (1440 minutes).", alias="maxSessionLifetimeMinutes")
    __properties = ["maxSessionIdleMinutes", "maxSessionLifetimeMinutes"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateSessionPolicyRequest:
        """Create an instance of UpdateSessionPolicyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if max_session_lifetime_minutes (nullable) is None
        # and __fields_set__ contains the field
        if self.max_session_lifetime_minutes is None and "max_session_lifetime_minutes" in self.__fields_set__:
            _dict['maxSessionLifetimeMinutes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateSessionPolicyRequest:
        """Create an instance of UpdateSessionPolicyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateSessionPolicyRequest.parse_obj(obj)

        _obj = UpdateSessionPolicyRequest.parse_obj({
            "max_session_idle_minutes": obj.get("maxSessionIdleMinutes"),
            "max_session_lifetime_minutes": obj.get("maxSessionLifetimeMinutes")
        })
        return _obj

UpdateSessionPolicyRequest.update_forward_refs()
