# coding: utf-8

"""
    FINBOURNE Identity Service API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_identity.models.mcp_tool_luminesce_payload import McpToolLuminescePayload
from finbourne_identity.models.mcp_tool_parameter import McpToolParameter
from finbourne_identity.models.mcp_tool_scheduler_payload import McpToolSchedulerPayload

class UpsertMcpToolRequest(BaseModel):
    """
    Request to create or update an MCP tool  # noqa: E501
    """
    name:  StrictStr = Field(...,alias="name", description="The name of the MCP tool (alphanumeric, underscore, and hyphen)") 
    title:  StrictStr = Field(...,alias="title", description="The title of the MCP tool") 
    description:  StrictStr = Field(...,alias="description", description="The description of the MCP tool") 
    destructive: Optional[StrictBool] = Field(default=None, description="Whether the tool is destructive")
    idempotent: Optional[StrictBool] = Field(default=None, description="Whether the tool is idempotent")
    open_world: Optional[StrictBool] = Field(default=None, description="Whether the tool operates in open world", alias="openWorld")
    read_only: Optional[StrictBool] = Field(default=None, description="Whether the tool is read-only", alias="readOnly")
    parameters: Optional[List[McpToolParameter]] = Field(default=None, description="The parameters for this MCP tool")
    luminesce_payload: Optional[McpToolLuminescePayload] = Field(default=None, alias="luminescePayload")
    scheduler_payload: Optional[McpToolSchedulerPayload] = Field(default=None, alias="schedulerPayload")
    __properties = ["name", "title", "description", "destructive", "idempotent", "openWorld", "readOnly", "parameters", "luminescePayload", "schedulerPayload"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpsertMcpToolRequest:
        """Create an instance of UpsertMcpToolRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in parameters (list)
        _items = []
        if self.parameters:
            for _item in self.parameters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['parameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of luminesce_payload
        if self.luminesce_payload:
            _dict['luminescePayload'] = self.luminesce_payload.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduler_payload
        if self.scheduler_payload:
            _dict['schedulerPayload'] = self.scheduler_payload.to_dict()
        # set to None if parameters (nullable) is None
        # and __fields_set__ contains the field
        if self.parameters is None and "parameters" in self.__fields_set__:
            _dict['parameters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpsertMcpToolRequest:
        """Create an instance of UpsertMcpToolRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpsertMcpToolRequest.parse_obj(obj)

        _obj = UpsertMcpToolRequest.parse_obj({
            "name": obj.get("name"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "destructive": obj.get("destructive"),
            "idempotent": obj.get("idempotent"),
            "open_world": obj.get("openWorld"),
            "read_only": obj.get("readOnly"),
            "parameters": [McpToolParameter.from_dict(_item) for _item in obj.get("parameters")] if obj.get("parameters") is not None else None,
            "luminesce_payload": McpToolLuminescePayload.from_dict(obj.get("luminescePayload")) if obj.get("luminescePayload") is not None else None,
            "scheduler_payload": McpToolSchedulerPayload.from_dict(obj.get("schedulerPayload")) if obj.get("schedulerPayload") is not None else None
        })
        return _obj

UpsertMcpToolRequest.update_forward_refs()
